#!/bin/bash

ln -s /var/www/crawl/allgames.txt cao-logfile-0.123
ln -s /home/crawl/chroot/var/games/crawl02/saves/milestones.txt cao-milestones-0.2
ln -s /home/crawl/chroot/var/games/crawl03/saves/milestones.txt cao-milestones-0.3

ln -s /home/crawl/chroot/var/games/crawl04/saves/logfile cao-logfile-0.4
ln -s /home/crawl/chroot/var/games/crawl04/saves/milestones.txt cao-milestones-0.4

ln -s /home/crawl/chroot/var/games/crawl05/saves/logfile cao-logfile-0.5
ln -s /home/crawl/chroot/var/games/crawl05/saves/milestones.txt cao-milestones-0.5

ln -s /home/crawl/chroot/var/games/crawl06/saves/logfile cao-logfile-0.6
ln -s /home/crawl/chroot/var/games/crawl06/saves/milestones.txt cao-milestones-0.6

ln -s /home/crawl/chroot/var/games/crawl07/saves/logfile cao-logfile-0.7
ln -s /home/crawl/chroot/var/games/crawl07/saves/milestones.txt cao-milestones-0.7
